### ISSUE TITLE
cURL error 28

### ISSUE THREAD

**Issue by Ghijoon** [stayforlong/hotelbeds#3]
Hi, 

I've added your configuration in composer.json
"autoload": {
        "classmap": ["database"],
        "psr-4": {
            "App\\": "app/",
            "StayForLong\\HotelBeds\\": "vendor/stayforlong/hotelbeds/src/"
        }
    },

When i'm using the hotel list:
$service_hotels_list = new \StayForLong\HotelBeds\ServiceHotelsList($request);
$response = $service_hotels_list();

It throws me an error of:
ServiceRequestException in ServiceRequest.php line 94:
cURL error 28: Operation timed out after 1000 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Any idea how to fix this? Thanks!
Oh and I'm using dev-master by the way,

**Comment by stayforlong** [comment]
Hi,

You need to increase the timeout defined in your ServiceRequest object.

By default is 1 second:
`public function __construct(ApiAuth $api_auth, $an_api_url, $an_api_params = [], $a_timeout = 1)`

Example:
`$request = new \StayForLong\HotelBeds\ServiceRequest($api_auth, $url_content, $api_params, $timeout = 10);`

Another option is to split the list of hotels and send small request each time.

**Comment by Ghijoon** [comment]
Worked like a charm!

Many thanks !! 
👍 

*p.s: for anyone got the error:
ServiceRequestException in ServiceRequest.php line 96:
<h1>596 Service Not Found</h1>

change 0.2 to 1.0 in url_content & url_hotels
